--- #YAML:1.0
name:               Arff-Util
version:            1.1
abstract:           ARFF files processing utilities.
author:
    - Ehsan Emadzadeh <ehsan0emadzadeh@yahoo.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:  2.12114
    Devel::Size:   0.71
    Moose:         0.92
    String::Util:  0.11
    Test::More:    0
    Text::CSV      0.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
